spring:  #Banco de Dados H2
    datasource:
        url: jdbc:h2:mem:sdw2025
        driver-class-name: org.h2.Driver
        username: sdw2025
        password:
    jpa:
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                '[format_sql]': true
                ddl-auto: create
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false 