#spring:
#    datasource:
#        url: jdbc:${DATABASE_URL}
#        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#        username: ${PGUSER}
#        password: ${PGPASSWORD}
#    jpa:
#        open-in-view: false
#        hibernate:
#                ddl-auto: create # validate / update / create / create-drop

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/API-REST
        username: postgres
        password: postgres        
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: create-drop # validate / update / create / create-drop
        generate-ddl: true
        show-sql: true
        open-in-view: false

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.tool.schema: debug

#spring:
#    datasource:
#        url: jdbc:h2:mem:sdw2025
#        username: sdw2025
#        password:
#    jpa:
#        show-sql: true
#        open-in-view: false
#        properties:
#            hibernate:
#                '[format_sql]': true
#                ddl-auto: create
#    h2:
#        console:
#            enabled: true
#            path: /h2-console
#            settings:
#                trace: false
#                web-allow-others: false 
