spring:  #Banco de Dados PostgreSQL localmente
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                ddl-auto: create-drop # validate / update / create / create-drop
        generate-ddl: true
        show-sql: true
        open-in-view: false
logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.tool.schema: debug